#!/bin/bash

# Функция для вывода справки
print_help() {
    echo "Использование: $0 [диск] [путь для сохранения]"
    echo ""
    echo "Параметры:"
    echo "  [диск]         Укажите диск, с которого будет сделан дамп, например: /dev/sda1"
    echo "  [путь для сохранения] Укажите путь и имя файла, в который будет сохранен дамп (например: /path/to/dump.img)"
    echo ""
    echo "Пример использования:"
    echo "  $0 /dev/sda1 /backups/sda1_backup.img"
    echo ""
    echo ""
    echo "*посмотреть список устройств $ sudo fdisk -l"
}

# Проверка на количество параметров
if [ $# -ne 2 ]; then
    echo "Ошибка: требуется два параметра."
    print_help
    exit 1
fi

# Входные параметры
disk=$1
output_path=$2

# Проверка существования исходного диска
if [ ! -b "$disk" ]; then
    echo "Ошибка: диск $disk не существует или не является блочным устройством."
    exit 1
fi

# Выполнение дампа
echo "Создание дампа с устройства $disk в файл $output_path ..."
dd if=$disk of=$output_path bs=64K conv=noerror,sync status=progress

# Проверка успешности выполнения
if [ $? -eq 0 ]; then
    echo "Дамп успешно создан: $output_path"
else
    echo "Ошибка при создании дампа."
    exit 1
fi
